### ISSUE TITLE
Trying to load this in version 4.2.2 fails

### ISSUE THREAD

**Issue by BuyMyMojo** [rayzorite/PlayerConnect#5]
Error:
```
 scene/resources/resource_format_text.cpp:1055 - res://Player Connect/Scenes/PlayerConnect.tscn:1 - Parse Error: Saved with newer format version
  Failed loading resource: res://Player Connect/Scenes/PlayerConnect.tscn. Make sure resources have been imported by opening the project in the editor at least once.
```

This comes from the scene using `format=4` but changing it back down to 3 throws another error complainging about the fembeded image sub resources.

What version of the engine is this even for?

**Comment by rayzorite** [comment]
hi, it was developed in 4.3 beta 1, i tested it in 4.1 and 4.0 and didn't have any problem. i will try to resolve this issue as soon as possible. Thanks for the report

**Comment by rayzorite** [comment]
I've tested again with different devices and different versions, the issue is not there.. if you elaborate it more maybe i can help

**Comment by BuyMyMojo** [comment]
https://github.com/rayzorite/PlayerConnect/assets/46948241/e4e6740b-4127-4344-8edb-8a2e83947056

Here is me live creating a new project and importing Player Connect in 4.2.2 without any sucess

Project files:
[Player Connect Test.zip](https://github.com/user-attachments/files/16022832/Player.Connect.Test.zip)

**Comment by rayzorite** [comment]
can you download this repository and open it in Godot and lemme know if the errors are still there..

this will help me narrow down the problem

**Comment by BuyMyMojo** [comment]
![image](https://github.com/rayzorite/PlayerConnect/assets/46948241/a498a6a5-121c-4f2b-b51b-4aa71434700d)
Exact same error with github verion

**Comment by rayzorite** [comment]
ok sorry to cause you troubles but i just found out Godot 4.3 changes .tscn format and so 4.3 projects cant be opened in previous versions.. i am working on making a different version for 4.0 - 4.2 versions.

**Comment by rayzorite** [comment]
ok sorry to cause you troubles but i just found out Godot 4.3 changes .tscn format and so 4.3 projects cant be opened in previous versions.. if u can move to 4.3 beta it would be great since 4.3 is soon launching anyways but i can understand if u wanna stick to older version.. i am currently busy with my own projects so dont have time to make 4.0 versions.. i am sorry i am changing version number from asset library to 4.3. Thanks for raising this issue

**Comment by BuyMyMojo** [comment]
Just a quick addition, I think I've found where the discrepancy in versions happened

they changed how PackedByteArrays are saved in the scene to reduce file size but since it's a change coming in 4.3 it doesn't support opening the new scenes in 4.2.2 and bellow if the new scene contains a PackedByteArray

https://godotengine.org/article/dev-snapshot-godot-4-3-beta-1/#packedbytearrays-saved-with-base64-encoding

**Comment by rayzorite** [comment]
Thanks for the information, When i get free i will look into making a separate version for 4.2 amd below
